#!/bin/bash
## variable declaration
person1=loukya
person2=vishruth
echo "$person1: hello $person2"
echo "$person2: hii $person1, hoe r u"
echo "$person1: i am good, how about u?"
echo "$person2:doing well thanks $person1"