#!/bin/bash
## variable declaration
person1=loukya
person2=vishruth
echo "shiva: hello madhu"
echo "madhu: hii shiva, hoe r u"
echo "shiva: i am good, how about u?"
echo "madhu:doing well thanks shiva"